[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.riscv64gc-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]

[target.powerpc64le-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.mips64el-unknown-linux-gnuabi64]
linker = "mips64el-linux-gnuabi64-gcc"
rustflags = ["-C", "target-feature=+crt-static"]
