[package]
name = "horiz-pkg"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }
clap = { version = "4.0", features = ["derive"] }
